# Generated by Django 2.2.3 on 2019-07-25 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_signup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='name',
            new_name='username',
        ),
    ]
