# Generated by Django 2.2.3 on 2019-07-25 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190725_0419'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('place', models.CharField(max_length=20)),
                ('number', models.IntegerField()),
            ],
        ),
    ]
