# Generated by Django 2.2.3 on 2019-07-27 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teqqet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('teqqet_Main_Img', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
